// Package asset localizes the images an article references.
//
// Images are roughly 80% of the archive's stored bytes, so the policy in this
// file *is* the storage budget. Every rule below is a decision about what a
// decade of reading is allowed to cost on disk.
//
// The pipeline: decide whether an image is worth keeping, fetch it, downscale
// it, transcode it, and store it under a content address. Nothing here decides
// *which* images to consider — that comes from the extracted body.
package asset

import (
	"fmt"
	"net/url"
	"strings"
)

// Policy thresholds from the asset policy.
const (
	// MaxDimension is the longest edge kept. Beyond this is resolution no
	// reader benefits from and every byte of which is stored forever.
	MaxDimension = 1600

	// MinBytes and MinDimension together identify images not worth keeping.
	//
	// Both must be true to skip: small *and* tiny. A 4KB image that is
	// 800 pixels wide is a well-optimized diagram and belongs in the archive;
	// a 4KB image that is 1×1 is a tracking pixel and does not. Requiring both
	// conditions is what keeps the rule from discarding good line art.
	MinBytes     = 10 << 10 // 10KB
	MinDimension = 100

	// MaxSVGBytes caps vector images, which are text and can be enormous when
	// generated by a plotting tool that embedded its whole dataset.
	MaxSVGBytes = 1 << 20 // 1MB

	// MaxSourceBytes caps any single image download. Larger than this is a
	// malfunction, not a photograph.
	MaxSourceBytes = 20 << 20 // 20MB
)

// SkipReason explains why an image was not localized. It is recorded so that
// "why is this image still hotlinked" has an answer.
type SkipReason string

// Skip reasons.
const (
	SkipNone         SkipReason = ""
	SkipDataURI      SkipReason = "data URI, already self-contained"
	SkipNotHTTP      SkipReason = "not an http or https URL"
	SkipTooSmall     SkipReason = "smaller than 10KB and under 100x100"
	SkipOversizeSVG  SkipReason = "SVG larger than 1MB"
	SkipOversizeFile SkipReason = "larger than 20MB"
	SkipUndecodable  SkipReason = "not a decodable image"
)

// ShouldFetch reports whether a reference is worth a network request at all.
//
// This is the cheap check, made before anything is downloaded. The expensive
// checks — dimensions, decodability — need the bytes and happen in Process.
func ShouldFetch(rawURL string) (bool, SkipReason) {
	trimmed := strings.TrimSpace(rawURL)

	if strings.HasPrefix(strings.ToLower(trimmed), "data:") {
		// The asset policy: data URIs are inlined as they are. The bytes are already in
		// the body, so fetching or rewriting them would achieve nothing.
		return false, SkipDataURI
	}

	u, err := url.Parse(trimmed)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return false, SkipNotHTTP
	}
	return true, SkipNone
}

// tooSmallToKeep implements the size rule against fetched bytes.
func tooSmallToKeep(byteSize, width, height int) bool {
	return byteSize < MinBytes && width < MinDimension && height < MinDimension
}

// SelectFromSrcset picks the best candidate from a srcset attribute.
//
// The asset policy: pick the candidate nearest MaxDimension and drop the rest. A responsive
// image offers the same picture at six sizes; archiving all six would multiply
// the storage cost of every article by six for no benefit, since the archive
// renders at one size.
//
// "Nearest" rather than "largest" is deliberate. The largest candidate is often
// a 3000-pixel original that will immediately be downscaled to 1600, so
// fetching it wastes bandwidth on both ends. The candidate closest to the
// target is the cheapest one that is good enough.
func SelectFromSrcset(srcset string) string {
	type candidate struct {
		url   string
		width int
	}

	var best candidate
	var bestDistance = -1

	for _, raw := range strings.Split(srcset, ",") {
		fields := strings.Fields(strings.TrimSpace(raw))
		if len(fields) == 0 {
			continue
		}

		c := candidate{url: fields[0]}
		if len(fields) > 1 {
			c.width = parseDescriptor(fields[1])
		}

		// A candidate with no width descriptor — a bare URL, or a pixel-density
		// descriptor like 2x — is treated as the target size, so that a srcset
		// of density variants still yields something.
		if c.width == 0 {
			c.width = MaxDimension
		}

		distance := c.width - MaxDimension
		if distance < 0 {
			distance = -distance
		}
		if bestDistance < 0 || distance < bestDistance {
			best, bestDistance = c, distance
		}
	}
	return best.url
}

// parseDescriptor reads the width from a srcset descriptor such as "1200w".
// Density descriptors ("2x") have no pixel width and return 0.
func parseDescriptor(descriptor string) int {
	if !strings.HasSuffix(descriptor, "w") {
		return 0
	}

	var width int
	if _, err := fmt.Sscanf(descriptor, "%dw", &width); err != nil {
		return 0
	}
	return width
}
